/**
 * @fileOverview Exports a set of icons from the `lucide-react` library.
 *
 * @module Icons
 *
 * @description This module provides a central place to import and export icons,
 * making it easier to use them throughout the application.
 */

import {
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  type LucideIcon,
  Gamepad,
  Heart,
  MapPin,
  ScanFace,
  Eye,
  MessageSquare,
  Zap,
  MessageCircle,
  Home,
  Award,
  Book,
  EyeOff,
  LogOut,
  ChevronDown,
  User as UserIcon,
  Settings as SettingsIcon,
  Instagram,
  Facebook,
  Cookie,
  Users,
  Mail,
  Shield,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: HelpCircle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  gitHub: Command,
  twitter: Twitter,
  check: Check,
  gamepad: Gamepad,
  heart: Heart,
  mapPin: MapPin,
  scanFace: ScanFace,
  eye: Eye,
  messageSquare: MessageSquare,
  zap: Zap,
  messageCircle: MessageCircle,
  home: Home,
  award: Award,
  book: Book,
  eyeOff: EyeOff,
  logOut: LogOut,
  chevronDown: ChevronDown,
  userIcon: UserIcon,
  settingsIcon: SettingsIcon,
  instagram: Instagram,
  facebook: Facebook,
  cookie: Cookie,
  users: Users,
  helpCircle: HelpCircle,
  mail: Mail,
  fileText: FileText,
  shield: Shield,
} as const;
